# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "first-floor"
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Nathan L. Walls"]
  s.date = "2012-04-22"
  s.description = "Takes care of the basic seven CRUD controller methods against HTML, XML, JSON and YAML. This was very useful with Rails 2.x. Under Rails 3 and later, this isn't quite as necessary, since rendering became a lot easier."
  s.email = "nathan@wallscorp.us"
  s.extra_rdoc_files = [
    "LICENSE",
    "README"
  ]
  s.files = [
    "LICENSE",
    "README",
    "Rakefile",
    "VERSION.yml",
    "doc/FirstFloor_ideas.oo3/contents.xml",
    "first-floor.gemspec",
    "lib/action_controller/first_floor.rb",
    "test/first_floor_test.rb",
    "test/test_helper.rb"
  ]
  s.homepage = "http://github.com/base10/first-floor"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.15"
  s.summary = "A little bit above ActionController::Base"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

